version: "3.3"  # optional since v1.27.0

networks:
  myZthombeapp:

services:
  web_api:
    build:
      context: .
      dockerfile: Zthombe-API/Dockerfile 
    container_name: web_api_application
    ports:
      - "5000:80"
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - 8002:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password